### PR TITLE
Fix: Install development dependencies on Travis as well

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] actually installs development dependencies on Travis

Blocks #4.

### CODE REVIEW

**Comment by DjThossi** [comment]
Currently there are no dev dependencies at the moment. So it is up to you if you want to solve this conflict or if you want to abandon this PR. I'm fine with both.

**Comment by localheinz** [comment]
Ha, right, my bad!

**Comment by localheinz** [comment]
Actually, if we want to use #4, then we need this. What do you think?

**Comment by DjThossi** [comment]
Thank you! I'll merge this now.

**Comment by localheinz** [comment]
Thank you, @DjThossi!

**Pull request merged**
