### PR TITLE
Fix: Leverage PSR-4 and flatten directory structure

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] fully leverages PSR-4 and flattens the directory structure

### CODE REVIEW

**Comment by DjThossi** [comment]
Could you change this PR against develop branch please? 
And please add yourself to Contributors list in README.md.

**Comment by localheinz** [comment]
Done! 🤓

**Review by DjThossi — APPROVED** [review]
Looks good to me. Thank you for your improvement

**Comment by localheinz** [comment]
Thank you, @DjThossi, especially for sharing here at the conference!

**Pull request merged**
