### PR TITLE
Fix: Require and run friendsofphp/php-cs-fixer on Travis

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] requires and runs `friendsofphp/php-cs-fixer` on Travis

### CODE REVIEW

**Comment by DjThossi** [comment]
Hey. I completely get your point but I removed php-cs-fixer as a dependency because travis failed on PHP nightly several times. So I went same way as using composer. I installed it globally. 
https://github.com/FriendsOfPHP/PHP-CS-Fixer#globally-manual
In this case the lib will not break in travis because php-cs-fixer is not required anymore

**Comment by localheinz** [comment]
@DjThossi 

How about 0a2b7b01ae4b141c8942b6872599290ef38112e5, then?

**Comment by DjThossi** [comment]
I really like your way of thinking. I'd love to see travis running it again. So would you be so kind and solve the conflict please? 

But my guess is that it would not solve the problem of php-cs-fixer breaking because usual issue is that php-cs-fixer has some wired setup of required php version inside comopser.json which can't be resolved properly for php nightly. Do you see a way in travis.yml to just run something like `compser require friendsofphp/php-cs-fixer` only in case of php version 5.6? In this way we could keep php-cs-fixer completely out of the composer.json

**Comment by localheinz** [comment]
@DjThossi 

Resolved!

Let's see if the build passes; if it doesn't, we can still remove `friendsofphp/php-cs-fixer` and only require it on Travis, then.

**Comment by DjThossi** [comment]
This solution looks perfect. Thank you.

**Comment by localheinz** [comment]
Thank you, @DjThossi!

**Pull request merged**
