### PR TITLE
Enhancement: Keep packages sorted

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] keeps packages in `composer.json` sorted (without the need to specify the `--sort-packages` option)

💁‍♂️ For reference, see https://getcomposer.org/doc/06-config.md#sort-packages.

### CODE REVIEW

**Review by DjThossi — APPROVED** [review]
Thank you!

**Comment by DjThossi** [comment]
This PR has a conflict in both files. Could you please resolve them?

**Comment by localheinz** [comment]
Rebased!

**Comment by DjThossi** [comment]
Don't worry. I'll merge now this PR and take the dev package out myself because I'd love to test some other stuff.

**Comment by localheinz** [comment]
Thank you, @DjThossi!

**Pull request merged**
