### PR TITLE
Ensure lean releases

### PR DESCRIPTION
**Pull request by raphaelstolt**
Excludes unnecessary files from releases/distributions.

### CODE REVIEW

**Comment by DjThossi** [comment]
Looks good but please add yourself to the list of contributors

**Comment by raphaelstolt** [comment]
And that's done how and where?

**Comment by DjThossi** [comment]
Oh I'm sorry I missed to tell you that the list of contributers is stored in README.md. Currently in develop branch.

**Comment by raphaelstolt** [comment]
Wondering why this is (or should be) required, as the list of contributors is available via GitHub's Graphs > Contributors tab.

**Comment by DjThossi** [comment]
I'm fine if you don't want to be on that list. It's just an offer.

**Comment by DjThossi** [comment]
Sorry wrong button

**Pull request merged**
